#!/bin/bash

source "/etc/sheep/watermains.sh"

#A_USERNAME="vbensch"
#B_USERNAME="MArL0"
#C_USERNAME="R1chard"
#D_USERNAME="WhatWouldKantDo"
#E_USERNAME="R0meo"
#F_USERNAME="B1golo"

CPU_SWITCH = "true"
CPU_USERNAME = $E_USERNAME
CPU_PASSWORD = $E_PASSWORD
CPU_MEMORY = "6000000000"
CPU_CORES = "6"
CPU_PRIORITY = "15"

GPU_SWITCH = true
GPU_USERNAME = F_USERNAME
GPU_PASSWORD = F_PASSWORD
GPU_MEMORY = 6000000000
GPU_CORES = 1
GPU_PRIORITY = 15

APU_SWITCH = false
APU_USERNAME = A_USERNAME
APU_PASSWORD = A_PASSWORD
APU_MEMORY = 12000000000
APU_CORES = 6
APU_PRIORITY = 15