#!/bin/bash

TAIL_USERNAME="vbensch"
TAIL_PASSWORD="2GintzUR30SrRBmzvFYxjdn9wMuI1VrmFICFz1NV"

#TAIL_USERNAME="MArL0"
#TAIL_PASSWORD="HrHBpvF8IR6bYHmXgycWLXf1zJQvrbjNGYANFeGc"

#TAIL_USERNAME="R1chard"
#TAIL_PASSWORD="YROWQgVZ3YyBrdoPoj9UL2u3XXdGwUwp7CgSvSbj"

#TAIL_USERNAME="WhatWouldKantDo"
#TAIL_PASSWORD="1WqOtJEYdJ0paXbiCKNg6neXwvqz1flSEdyo2PCh"

#TAIL_USERNAME="R0meo"
#TAIL_PASSWORD="cT3IAlE1ogm002M9NjDYoINfQgELgUreLMQ6ivvm"
