#!/bin/bash

A_USERNAME="vbensch"
A_PASSWORD="2GintzUR30SrRBmzvFYxjdn9wMuI1VrmFICFz1NV"

B_USERNAME="MArL0"
B_PASSWORD="HrHBpvF8IR6bYHmXgycWLXf1zJQvrbjNGYANFeGc"

C_USERNAME="R1chard"
C_PASSWORD="YROWQgVZ3YyBrdoPoj9UL2u3XXdGwUwp7CgSvSbj"

D_USERNAME="WhatWouldKantDo"
D_PASSWORD="1WqOtJEYdJ0paXbiCKNg6neXwvqz1flSEdyo2PCh"

E_USERNAME="R0meo"
E_PASSWORD="cT3IAlE1ogm002M9NjDYoINfQgELgUreLMQ6ivvm"

F_USERNAME="B1golo"
F_PASSWORD="dyZTBL7ILL0iKwLDLV3m9LVvhpq5BeYE9HVDyTrn"

GPU_COMMAND="-compute-method GPU -gpu CUDA_0"
CPU_COMMAND="-compute-method CPU"
APU_COMMAND="-compute-method CPU_GPU -gpu CUDA_0"